# Generated by Django 5.0.6 on 2025-03-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
